# basic

In [36]:
import pandas as pd

In [37]:
# list 스러운것
a = pd.Series([1,123,543,213890])
a

0         1
1       123
2       543
3    213890
dtype: int64

In [38]:
a[2]

np.int64(543)

In [39]:
df = pd.DataFrame()
df["이름"]=["새우깡","양파링"]
df["가격"]=[3000,4000]
print(df)

    이름    가격
0  새우깡  3000
1  양파링  4000

In [40]:
df["이름"]  # 인덱스가 나옴

0    새우깡
1    양파링
Name: 이름, dtype: object

In [41]:
b = df.set_index(df["이름"])   # 이름필드로 인덱스로 사용함. 원본데이터에 영향 안가는걸 추구(이뮤터블) 그러므로 변수에 담아서 사용하자
b

      이름    가격
이름
새우깡  새우깡  3000
양파링  양파링  4000

In [43]:
b.loc["새우깡"]

이름     새우깡
가격    3000
Name: 새우깡, dtype: object

In [45]:
b.iloc[1]

이름     양파링
가격    4000
Name: 양파링, dtype: object

# make

In [46]:
import numpy as np

In [52]:
df = pd.DataFrame()
df["이름"]=["새우깡","양파링"]
df["가격"]=[3000,4000]
df

    이름    가격
0  새우깡  3000
1  양파링  4000

In [53]:
df2 = pd.DataFrame()
df2["이름"] = np.array(["홍길동","김길동"])
df2["나이"] = np.array([20,30])
df2

    이름  나이
0  홍길동  20
1  김길동  30

In [61]:
#2차원  list/np.array
c = [["홍길동",20],["김길동",30]]
# print(c)
c = pd.DataFrame(c)
# 컬럼이 안나옴
print(c)

     0   1
0  홍길동  20
1  김길동  30

In [63]:
c = [["홍길동",20],["김길동",30]]
c = pd.DataFrame(c, columns =['이름','나이'])
print(c)

    이름  나이
0  홍길동  20
1  김길동  30

In [65]:
d={
   "이름":["홍길동","김길동"],
   "나이":[20,30]
  }
d = pd.DataFrame(d)
d

    이름  나이
0  홍길동  20
1  김길동  30

In [67]:
e = [
     {'이름':'홍갈동','나이':20},
     {'이름':'김길동','나이':30},
    ]
e=  pd.DataFrame(e)
print(e)

    이름  나이
0  홍갈동  20
1  김길동  30