In [1]:
import pandas as pd

a = pd.read_csv("./titanic.csv")

In [2]:
a

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [20]:
b=pd.read_csv('../numpy/seoulDust.csv', names= ["년월일시간","권역","구","미세","초미세","상태"])
b

                   년월일시간   권역     구  미세  초미세   상태
0    2025-11-19 13:30:03  도심권    중구  23   12   보통
1    2025-11-19 13:30:03  도심권   종로구  37   19   보통
2    2025-11-19 13:30:03  도심권   용산구  39   16   보통
3    2025-11-19 13:30:03  서북권   은평구  20   10   좋음
4    2025-11-19 13:30:03  서북권  서대문구  24   11   보통
..                   ...  ...   ...  ..  ...  ...
668  2025-12-03 13:30:02  서남권   양천구   0    0  NaN
669  2025-12-03 13:30:02  동남권   강남구  17    8   좋음
670  2025-12-03 13:30:02  동남권   서초구  34   12   좋음
671  2025-12-03 13:30:02  동남권   송파구  21    9   좋음
672  2025-12-03 13:30:02  동남권   강동구  27    8   보통

[673 rows x 6 columns]

## txt 파일도 read_csv  sep로 정렬해서 pandas로 사용 가능

In [24]:

c = pd.read_csv("./naverBlog.txt" , sep="\t", names=["제목","내용","광고"])        
c

,제목,내용,광고
0,양양 죽도 맛집 평정한 사랑대게,양양 죽도 맛집 평정한 사랑대게 양양 죽도 맛집 평정한 사랑대게 양양 죽도 맛집 평...,광고
1,끝내줬던 필리핀 보홀 씨푸드 맛집,서비스를 제공받아 작성되었습니다 오늘은 제가 보홀을 여행할 때 방문했던 보홀 씨푸드...,광고
2,마곡 맛집 뷰 좋고 삼겹살 맛있는 돈구멍,#마곡맛집 #돈구멍 삼겹살 맛있는 #마곡뷰맛집 얏호~ 간만 세 식구 마곡 맛집에서 ...,정상
3,대부도 맛집 알차게 즐긴 풍경,지난 주 대부도 현지 분들 사이에서 유명하다는 대부도 맛집 에 찾아갔어요. 다양한 ...,정상
4,강릉 로컬 맛집 기대했던 교동대게,강릉 로컬 맛집 기대했던 교동대게 강릉 로컬 맛집 기대했던 교동대게 강릉 로컬 맛집...,광고
5,대전 유성구 봉명동 맛집 방문 후기,대전 유성구 봉명동 맛집 베이징덕 방문 후기 갑자기 더운 날씨에 감기가 걸려 몸이 ...,정상
6,양양 설해원 맛집 살이 꽉 찬 서핑크랩,#양양설해원맛집 #서핑크랩 얼마 전 친구들과 함께 양양 설해원 맛집을 방문했어요. ...,정상
7,"부산여행, 기장맛집! 일광소나무집:)",포스팅쓰기전부터 사진고르면서 입에 침이 막 고이기시작했어요:) 제가 맛집 리뷰를 그...,광고
8,이천 맛집 분위기 황홀했던 경춘당,이천 맛집 분위기 황홀했던 경춘당 지난 주말 이천으로 1박 2일 여행을 다녀왔어요....,광고
9,여수 간장게장 맛집 추천 대감게장,여수 간장게장 맛집 추천 대감게장 25년 전통의 여수 게장 맛집이 있다고 해서 여수...,정상

                SD_DATE SD_MSRRGN_NM SD_MSRSTE_NM  SD_PM10  SD_PM25  \
0   2025-11-19 13:30:03          도심권           중구       23       12
1   2025-11-19 13:30:03          도심권          종로구       37       19
2   2025-11-19 13:30:03          도심권          용산구       39       16
3   2025-11-19 13:30:03          서북권          은평구       20       10
4   2025-11-19 13:30:03          서북권         서대문구       24       11
..                  ...          ...          ...      ...      ...
668 2025-12-03 13:30:02          서남권          양천구        0        0
669 2025-12-03 13:30:02          동남권          강남구       17        8
670 2025-12-03 13:30:02          동남권          서초구       34       12
671 2025-12-03 13:30:02          동남권          송파구       21        9
672 2025-12-03 13:30:02          동남권          강동구       27        8

    SD_INDEX_NM
0            보통
1            보통
2            보통
3            좋음
4            보통
..          ...
668        None
669          좋음
670          좋음
671          좋음
672          보통

[673 rows x 6 columns]

C:\Users\soldesk\AppData\Local\Temp\ipykernel_15012\2890152438.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  d= pd.read_sql(sql,con)