In [ ]:
import pandas as pd
a =pd.read_csv("../numpy/subway.csv",names=['년','월','일','호선','역','인풋','아웃풋'])
df = pd.DataFrame(a)

In [3]:

print(df)

# 데이터 어떻게 생겼나  -> 마지막 데이터 3개만 보기
print(df.tail(3))

# 언제부터 모은 데이터인가 -> 첫데이터 날짜만
print(df.head(1)[["년","월","일"]])

#100~110번데이터 노선번호 역이름
print(df.iloc[100:111][["호선","역"]])

            년   월   일   호선     역     인풋    아웃풋
0        2015   1   1  1호선   서울역  47071  40197
1        2015   1   1  1호선    시청  11016   8943
2        2015   1   1  1호선    종각  22084  17648
3        2015   1   1  1호선  종로3가  17917  15817
4        2015   1   1  1호선  종로5가   9789   9216
...       ...  ..  ..  ...   ...    ...    ...
2143338  2024  12  31  중앙선    오빈    275    289
2143339  2024  12  31  중앙선    양평   3110   3426
2143340  2024  12  31  중앙선    원덕    307    294
2143341  2024  12  31  중앙선    용문   1751   1947
2143342  2024  12  31  중앙선    지평     52     76

[2143343 rows x 7 columns]
            년   월   일   호선   역    인풋   아웃풋
2143340  2024  12  31  중앙선  원덕   307   294
2143341  2024  12  31  중앙선  용문  1751  1947
2143342  2024  12  31  중앙선  지평    52    76
      년  월  일
0  2015  1  1
      호선          역
100  4호선      미아사거리
101  4호선         길음
102  4호선     성신여대입구
103  4호선      한성대입구
104  4호선         혜화
105  4호선        동대문
106  4호선  동대문역사문화공원
107  4호선        충무로
108  4호선         명동
109  4호선         회현
110  4호선        서울역

            년   월   일   호선     역     인풋    아웃풋
0        2015   1   1  1호선   서울역  47071  40197
1        2015   1   1  1호선    시청  11016   8943
2        2015   1   1  1호선    종각  22084  17648
3        2015   1   1  1호선  종로3가  17917  15817
4        2015   1   1  1호선  종로5가   9789   9216
...       ...  ..  ..  ...   ...    ...    ...
2143338  2024  12  31  중앙선    오빈    275    289
2143339  2024  12  31  중앙선    양평   3110   3426
2143340  2024  12  31  중앙선    원덕    307    294
2143341  2024  12  31  중앙선    용문   1751   1947
2143342  2024  12  31  중앙선    지평     52     76

[2143343 rows x 7 columns]

In [16]:
df[df["호선"] == "3호선"]

            년   월   일   호선     역     인풋    아웃풋
60       2015   1   1  3호선    지축    515    538
61       2015   1   1  3호선   구파발   6879   6260
62       2015   1   1  3호선   연신내  20031  19470
63       2015   1   1  3호선    불광   9519  11029
64       2015   1   1  3호선    녹번   6115   5558
...       ...  ..  ..  ...   ...    ...    ...
2142817  2024  12  31  3호선    일원  11221  10573
2142818  2024  12  31  3호선    수서  18546  18005
2142819  2024  12  31  3호선  가락시장   9188   8898
2142820  2024  12  31  3호선  경찰병원   7288   7173
2142821  2024  12  31  3호선    오금   6325   5551

[123257 rows x 7 columns]

In [8]:
df[df["호선"]=="2호선"][["역","인풋","아웃풋"]]

                 역     인풋    아웃풋
10              시청   8152   5656
11           을지로입구  22859  22023
12           을지로3가   5524   5322
13           을지로4가   3322   3021
14       동대문역사문화공원  10470  11541
...            ...    ...    ...
2142783        신설동   3449   3347
2142784        도림천   1315   1406
2142785       양천구청   6657   6776
2142786      신정네거리  10244  10360
2142787  용두(동대문구청)   2748   2741

[182650 rows x 3 columns]

In [9]:
df[df["인풋"]>50000]

            년   월   일   호선        역     인풋    아웃풋
48       2015   1   1  2호선     홍대입구  57469  51756
539      2015   1   2  1호선      서울역  76413  67738
541      2015   1   2  1호선       종각  56891  55013
550      2015   1   2  2호선    을지로입구  61578  60449
562      2015   1   2  2호선       강변  54823  54079
...       ...  ..  ..  ...      ...    ...    ...
2142759  2024  12  31  2호선       강남  78880  78930
2142767  2024  12  31  2호선       신림  57972  55620
2142769  2024  12  31  2호선  구로디지털단지  58260  57154
2142771  2024  12  31  2호선      신도림  50735  48907
2142776  2024  12  31  2호선     홍대입구  74591  94345

[38848 rows x 7 columns]

In [12]:
df[df["아웃풋"]<50][['년','월','일','역']]

            년   월   일    역
340      2015   1   1   옥수
481      2015   1   1   달월
713      2015   1   2  연신내
880      2015   1   2   옥수
1151     2015   1   3  충무로
...       ...  ..  ..  ...
2142800  2024  12  31  충무로
2143104  2024  12  31   창동
2143149  2024  12  31  임진강
2143150  2024  12  31   운천
2143219  2024  12  31   복정

[17633 rows x 4 columns]

In [17]:
df[df["역"]=="종각"]

            년   월   일   호선   역     인풋    아웃풋
2        2015   1   1  1호선  종각  22084  17648
541      2015   1   2  1호선  종각  56891  55013
1081     2015   1   3  1호선  종각  35352  32763
1625     2015   1   4  1호선  종각  23670  19905
2166     2015   1   5  1호선  종각  59170  57163
...       ...  ..  ..  ...  ..    ...    ...
2140259  2024  12  27  1호선  종각  43756  42811
2140876  2024  12  28  1호선  종각  43539  37458
2141495  2024  12  29  1호선  종각  16809  15135
2142114  2024  12  30  1호선  종각  41480  39951
2142730  2024  12  31  1호선  종각  41994  42616

[3653 rows x 7 columns]

In [21]:
# 역명에 입구들어가는 데이터
df[df["역"].str.contains("입구")]

            년   월   일        호선           역     인풋    아웃풋
11       2015   1   1       2호선       을지로입구  22859  22023
21       2015   1   1       2호선        건대입구  28295  28851
37       2015   1   1       2호선       서울대입구  24831  25799
48       2015   1   1       2호선        홍대입구  57469  51756
72       2015   1   1       3호선        동대입구   5303   6138
...       ...  ..  ..       ...         ...    ...    ...
2143129  2024  12  31       경의선        홍대입구   2196   2723
2143168  2024  12  31       경인선  온수(성공회대입구)   6521   5877
2143192  2024  12  31  공항철도 1호선        홍대입구  15310  15350
2143217  2024  12  31       분당선       대모산입구   5625   5166
2143302  2024  12  31     우이신설선  성신여대입구(돈암)   3981   4551

[89438 rows x 7 columns]

In [25]:
#역명이 서울로 시작하는 데이터 역명, 탄사람,내린사람수 
df[df['역'].str.startswith("서울")][['인풋','아웃풋']]

            인풋    아웃풋
0        47071  40197
37       24831  25799
110       3943  10823
366       1789   1084
428      12059  12439
...        ...    ...
2143124   3238   4465
2143190  13345  12005
2143221  11345  11528
2143270   3088   3266
2143277  10582   9127

[27434 rows x 2 columns]